### Q1. Load the CSV file and display first 5 rows.

In [86]:
# Write your answer here
import pandas as pd
data = pd.read_csv("sales_data_project_big.csv")
data.head()

   OrderID   Product     Category  Quantity  Price   OrderDate       City
0     1001  Keyboard  Accessories         1   1500  07-01-2023       Pune
1     1002    Mobile  Electronics         2  22000  05-02-2023      Delhi
2     1003  Keyboard  Accessories         1   1500  01-06-2023  Bangalore
3     1004    Laptop  Electronics         1  65000  24-01-2023     Mumbai
4     1005    Mobile  Electronics         1  22000  24-05-2023     Mumbai

### Q2. Display basic information of the dataset.

In [87]:
# Write your answer here
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    40 non-null     int64
 1   Product    40 non-null     object
 2   Category   40 non-null     object
 3   Quantity   40 non-null     int64
 4   Price      40 non-null     int64
 5   OrderDate  40 non-null     object
 6   City       40 non-null     object
dtypes: int64(3), object(4)
memory usage: 2.3+ KB

### Q3. Check for missing values column-wise.

In [88]:
# Write your answer here
data.isna()

    OrderID  Product  Category  Quantity  Price  OrderDate   City
0     False    False     False     False  False      False  False
1     False    False     False     False  False      False  False
2     False    False     False     False  False      False  False
3     False    False     False     False  False      False  False
4     False    False     False     False  False      False  False
5     False    False     False     False  False      False  False
6     False    False     False     False  False      False  False
7     False    False     False     False  False      False  False
8     False    False     False     False  False      False  False
9     False    False     False     False  False      False  False
10    False    False     False     False  False      False  False
11    False    False     False     False  False      False  False
12    False    False     False     False  False      False  False
13    False    False     False     False  False      False  False
14    False    False     False     False  False      False  False
15    False    False     False     False  False      False  False
16    False    False     False     False  False      False  False
17    False    False     False     False  False      False  False
18    False    False     False     False  False      False  False
19    False    False     False     False  False      False  False
20    False    False     False     False  False      False  False
21    False    False     False     False  False      False  False
22    False    False     False     False  False      False  False
23    False    False     False     False  False      False  False
24    False    False     False     False  False      False  False
25    False    False     False     False  False      False  False
26    False    False     False     False  False      False  False
27    False    False     False     False  False      False  False
28    False    False     False     False  False      False  False
29    False    False     False     False  False      False  False
30    False    False     False     False  False      False  False
31    False    False     False     False  False      False  False
32    False    False     False     False  False      False  False
33    False    False     False     False  False      False  False
34    False    False     False     False  False      False  False
35    False    False     False     False  False      False  False
36    False    False     False     False  False      False  False
37    False    False     False     False  False      False  False
38    False    False     False     False  False      False  False
39    False    False     False     False  False      False  False

### Q4. Convert OrderDate column to datetime.

In [89]:
# Write your answer here
data['OrderDate'] = pd.to_datetime(data['OrderDate'], dayfirst=True)

### Q5. Create a new column TotalAmount = Quantity * Price.

In [90]:
# Write your answer here
data['TotalAmount']=data['Quantity']*data['Price']

### Q6. Find total revenue generated.

In [91]:
# Write your answer here
total_revenue = data['TotalAmount'].sum()
total_revenue

np.int64(1874000)

### Q7. Find average order value.

In [92]:
# Write your answer here
data['TotalAmount'].mean()

np.float64(46850.0)

### Q8. Find city-wise total revenue.

In [93]:
# Write your answer here
data.groupby("City", as_index=False)["TotalAmount"].sum()

        City  TotalAmount
0  Bangalore       216000
1    Chennai        33000
2      Delhi       409000
3     Mumbai       411000
4       Pune       805000

### Q9. Find product-wise total revenue.

In [94]:
# Write your answer here
data.groupby("Product", as_index=False)["TotalAmount"].sum()

      Product  TotalAmount
0  Headphones        30000
1    Keyboard        36000
2      Laptop       910000
3      Mobile       462000
4  Smartwatch       136000
5      Tablet       300000

### Q10. Find category-wise total revenue.

In [95]:
# Write your answer here
data.groupby("Category", as_index=False)["TotalAmount"].sum()

      Category  TotalAmount
0  Accessories       202000
1  Electronics      1672000

### Q11. Find top 5 highest revenue orders.

In [96]:
# Write your answer here
data.sort_values("TotalAmount", ascending=False).head(5)

,OrderID,Product,Category,Quantity,Price,OrderDate,City,TotalAmount
9,1010,Laptop,Electronics,4,65000,2023-01-25,Pune,260000
22,1023,Laptop,Electronics,3,65000,2023-04-13,Pune,195000
14,1015,Laptop,Electronics,2,65000,2023-03-16,Delhi,130000
23,1024,Laptop,Electronics,2,65000,2023-05-26,Pune,130000
29,1030,Laptop,Electronics,2,65000,2023-06-10,Mumbai,130000

### Q12. Find most sold product by quantity.

In [97]:
# Write your answer here
data.groupby("Product")["Quantity"].sum().sort_values(ascending=False)

Product
Keyboard      24
Mobile        21
Smartwatch    17
Laptop        14
Headphones    12
Tablet        10
Name: Quantity, dtype: int64

### Q13. Find least sold product by quantity.

In [98]:
# Write your answer here
data.groupby("Product")["Quantity"].sum().sort_values(ascending=True)

Product
Tablet        10
Headphones    12
Laptop        14
Smartwatch    17
Mobile        21
Keyboard      24
Name: Quantity, dtype: int64

### Q14. Find month-wise total revenue.

In [99]:
# Write your answer here
data.groupby(data["OrderDate"].dt.to_period("M"))["TotalAmount"].sum()

OrderDate
2023-01    684500
2023-02    142500
2023-03    180000
2023-04    350000
2023-05    185000
2023-06    332000
Freq: M, Name: TotalAmount, dtype: int64

### Q15. Extract month name from OrderDate.

In [100]:
# Write your answer here
data['MonthName'] = data['OrderDate'].dt.month_name()

### Q16. Find city and product combination with highest revenue.

In [101]:
combo_revenue_df = (
    data.groupby(["City", "Product"], as_index=False)["TotalAmount"]
    .sum()
    .sort_values("TotalAmount", ascending=False)
)

combo_revenue_df.head(1)

    City Product  TotalAmount
20  Pune  Laptop       585000

### Q17. Find percentage contribution of each city to total revenue.

In [102]:
# Write your answer here
city_rev = data.groupby("City")["TotalAmount"].sum()
(city_rev / city_rev.sum()) * 100

City
Bangalore    11.526147
Chennai       1.760939
Delhi        21.824973
Mumbai       21.931697
Pune         42.956243
Name: TotalAmount, dtype: float64

### Q18. Find percentage contribution of each product to total revenue.

In [103]:
# Write your answer here
prod_rev = data.groupby("Product")["TotalAmount"].sum()
(prod_rev / prod_rev.sum()) * 100

Product
Headphones     1.600854
Keyboard       1.921025
Laptop        48.559232
Mobile        24.653148
Smartwatch     7.257204
Tablet        16.008538
Name: TotalAmount, dtype: float64

### Q19. Normalize TotalAmount column.

In [104]:
# Write your answer here
data["TotalAmount_Normalized"] = (
    (data["TotalAmount"] - data["TotalAmount"].min()) /
    (data["TotalAmount"].max() - data["TotalAmount"].min())
)

### Q20. Find correlation between Quantity and TotalAmount.

In [105]:
# Write your answer here
data["Quantity"].corr(data["TotalAmount"])

np.float64(0.2458345505991147)

### Q21. Find orders where TotalAmount is above average.

In [106]:
# Write your answer here
data[data["TotalAmount"] > data["TotalAmount"].mean()]

,OrderID,Product,Category,Quantity,Price,OrderDate,City,TotalAmount,MonthName,TotalAmount_Normalized
3,1004,Laptop,Electronics,1,65000,2023-01-24,Mumbai,65000,January,0.245648
9,1010,Laptop,Electronics,4,65000,2023-01-25,Pune,260000,January,1.000000
10,1011,Tablet,Electronics,3,30000,2023-01-12,Bangalore,90000,January,0.342360
13,1014,Tablet,Electronics,2,30000,2023-06-30,Delhi,60000,June,0.226306
14,1015,Laptop,Electronics,2,65000,2023-03-16,Delhi,130000,March,0.497099
17,1018,Tablet,Electronics,2,30000,2023-06-21,Pune,60000,June,0.226306
21,1022,Mobile,Electronics,3,22000,2023-01-15,Mumbai,66000,January,0.249516
22,1023,Laptop,Electronics,3,65000,2023-04-13,Pune,195000,April,0.748549
23,1024,Laptop,Electronics,2,65000,2023-05-26,Pune,130000,May,0.497099
24,1025,Mobile,Electronics,4,22000,2023-04-12,Bangalore,88000,April,0.334623
25,1026,Mobile,Electronics,3,22000,2023-02-05,Mumbai,66000,February,0.249516
28,1029,Mobile,Electronics,4,22000,2023-01-24,Delhi,88000,January,0.334623
29,1030,Laptop,Electronics,2,65000,2023-06-10,Mumbai,130000,June,0.497099
34,1035,Tablet,Electronics,3,30000,2023-01-29,Pune,90000,January,0.342360

### Q22. Create a pivot table (City vs Category) with total revenue.

In [107]:
# Write your answer here
pd.pivot_table(
    data,
    values="TotalAmount",
    index="City",
    columns="Category",
    aggfunc="sum"
)

Category   Accessories  Electronics
City
Bangalore      38000.0     178000.0
Chennai        33000.0          NaN
Delhi          43000.0     366000.0
Mumbai         62000.0     349000.0
Pune           26000.0     779000.0

### Q23. Find rolling 3-order average of TotalAmount.

In [108]:
# Write your answer here
data["Rolling_Avg"] = data["TotalAmount"].rolling(3).mean()
data

,OrderID,Product,Category,Quantity,Price,OrderDate,City,TotalAmount,MonthName,TotalAmount_Normalized,Rolling_Avg
0,1001,Keyboard,Accessories,1,1500,2023-01-07,Pune,1500,January,0.000000,NaN
1,1002,Mobile,Electronics,2,22000,2023-02-05,Delhi,44000,February,0.164410,NaN
2,1003,Keyboard,Accessories,1,1500,2023-06-01,Bangalore,1500,June,0.000000,15666.666667
3,1004,Laptop,Electronics,1,65000,2023-01-24,Mumbai,65000,January,0.245648,36833.333333
4,1005,Mobile,Electronics,1,22000,2023-05-24,Mumbai,22000,May,0.079304,29500.000000
5,1006,Keyboard,Accessories,4,1500,2023-02-26,Bangalore,6000,February,0.017408,31000.000000
6,1007,Smartwatch,Accessories,3,8000,2023-01-02,Mumbai,24000,January,0.087041,17333.333333
7,1008,Keyboard,Accessories,4,1500,2023-03-29,Pune,6000,March,0.017408,12000.000000
8,1009,Mobile,Electronics,2,22000,2023-03-28,Delhi,44000,March,0.164410,24666.666667
9,1010,Laptop,Electronics,4,65000,2023-01-25,Pune,260000,January,1.000000,103333.333333
10,1011,Tablet,Electronics,3,30000,2023-01-12,Bangalore,90000,January,0.342360,131333.333333
11,1012,Smartwatch,Accessories,1,8000,2023-04-07,Delhi,8000,April,0.025145,119333.333333
12,1013,Smartwatch,Accessories,3,8000,2023-06-10,Chennai,24000,June,0.087041,40666.666667
13,1014,Tablet,Electronics,2,30000,2023-06-30,Delhi,60000,June,0.226306,30666.666667
14,1015,Laptop,Electronics,2,65000,2023-03-16,Delhi,130000,March,0.497099,71333.333333
15,1016,Mobile,Electronics,1,22000,2023-04-08,Pune,22000,April,0.079304,70666.666667
16,1017,Headphones,Accessories,3,2500,2023-02-11,Pune,7500,February,0.023211,53166.666667
17,1018,Tablet,Electronics,2,30000,2023-06-21,Pune,60000,June,0.226306,29833.333333
18,1019,Keyboard,Accessories,1,1500,2023-06-05,Mumbai,1500,June,0.000000,23000.000000
19,1020,Smartwatch,Accessories,2,8000,2023-02-11,Bangalore,16000,February,0.056093,25833.333333
20,1021,Headphones,Accessories,3,2500,2023-06-13,Chennai,7500,June,0.023211,8333.333333
21,1022,Mobile,Electronics,3,22000,2023-01-15,Mumbai,66000,January,0.249516,29833.333333
22,1023,Laptop,Electronics,3,65000,2023-04-13,Pune,195000,April,0.748549,89500.000000
23,1024,Laptop,Electronics,2,65000,2023-05-26,Pune,130000,May,0.497099,130333.333333
24,1025,Mobile,Electronics,4,22000,2023-04-12,Bangalore,88000,April,0.334623,137666.666667
25,1026,Mobile,Electronics,3,22000,2023-02-05,Mumbai,66000,February,0.249516,94666.666667
26,1027,Keyboard,Accessories,3,1500,2023-05-30,Bangalore,4500,May,0.011605,52833.333333
27,1028,Smartwatch,Accessories,4,8000,2023-04-03,Mumbai,32000,April,0.117988,34166.666667
28,1029,Mobile,Electronics,4,22000,2023-01-24,Delhi,88000,January,0.334623,41500.000000
29,1030,Laptop,Electronics,2,65000,2023-06-10,Mumbai,130000,June,0.497099,83333.333333
30,1031,Keyboard,Accessories,4,1500,2023-06-02,Delhi,6000,June,0.017408,74666.666667
31,1032,Headphones,Accessories,4,2500,2023-06-02,Bangalore,10000,June,0.032882,48666.666667
32,1033,Smartwatch,Accessories,3,8000,2023-05-22,Delhi,24000,May,0.087041,13333.333333
33,1034,Keyboard,Accessories,1,1500,2023-06-24,Chennai,1500,June,0.000000,11833.333333
34,1035,Tablet,Electronics,3,30000,2023-01-29,Pune,90000,January,0.342360,38500.000000
35,1036,Headphones,Accessories,2,2500,2023-04-27,Delhi,5000,April,0.013540,32166.666667
36,1037,Keyboard,Accessories,3,1500,2023-05-09,Mumbai,4500,May,0.011605,33166.666667
37,1038,Smartwatch,Accessories,1,8000,2023-06-10,Pune,8000,June,0.025145,5833.333333
38,1039,Keyboard,Accessories,2,1500,2023-02-09,Pune,3000,February,0.005803,5166.666667
39,1040,Mobile,Electronics,1,22000,2023-06-03,Pune,22000,June,0.079304,11000.000000

### Q24. Rank orders based on TotalAmount.

In [109]:
# Write your answer here
data["Revenue_Rank"] = data["TotalAmount"].rank(ascending=False)

### Q25. Find cumulative revenue over time.

In [110]:
# Write your answer here
data.sort_values("OrderDate", inplace=True)
data["Cumulative_Revenue"] = data["TotalAmount"].cumsum()

### Q26. Detect outlier orders using IQR method.

In [111]:
# Write your answer here
Q1 = data["TotalAmount"].quantile(0.25)
Q3 = data["TotalAmount"].quantile(0.75)
IQR = Q3 - Q1

outliers = data[
    (data["TotalAmount"] < Q1 - 1.5*IQR) |
    (data["TotalAmount"] > Q3 + 1.5*IQR)
]
outliers

,OrderID,Product,Category,Quantity,Price,OrderDate,City,TotalAmount,MonthName,TotalAmount_Normalized,Rolling_Avg,Revenue_Rank,Cumulative_Revenue
9,1010,Laptop,Electronics,4,65000,2023-01-25,Pune,260000,January,1.000000,103333.333333,1.0,594500
22,1023,Laptop,Electronics,3,65000,2023-04-13,Pune,195000,April,0.748549,89500.000000,2.0,1352000

### Q27. Sort data by OrderDate and TotalAmount.

In [112]:
# Write your answer here
data.sort_values(
    by=["OrderDate", "TotalAmount"],
    ascending=[True, False],
    inplace=True
)

### Q28. Filter orders from last 2 months.

In [113]:
# Write your answer here
latest = data["OrderDate"].max()
data[data["OrderDate"] >= latest - pd.DateOffset(months=2)]

,OrderID,Product,Category,Quantity,Price,OrderDate,City,TotalAmount,MonthName,TotalAmount_Normalized,Rolling_Avg,Revenue_Rank,Cumulative_Revenue
36,1037,Keyboard,Accessories,3,1500,2023-05-09,Mumbai,4500,May,0.011605,33166.666667,34.5,1361500
32,1033,Smartwatch,Accessories,3,8000,2023-05-22,Delhi,24000,May,0.087041,13333.333333,19.0,1385500
4,1005,Mobile,Electronics,1,22000,2023-05-24,Mumbai,22000,May,0.079304,29500.000000,22.0,1407500
23,1024,Laptop,Electronics,2,65000,2023-05-26,Pune,130000,May,0.497099,130333.333333,4.0,1537500
26,1027,Keyboard,Accessories,3,1500,2023-05-30,Bangalore,4500,May,0.011605,52833.333333,34.5,1542000
2,1003,Keyboard,Accessories,1,1500,2023-06-01,Bangalore,1500,June,0.000000,15666.666667,38.5,1543500
31,1032,Headphones,Accessories,4,2500,2023-06-02,Bangalore,10000,June,0.032882,48666.666667,25.0,1553500
30,1031,Keyboard,Accessories,4,1500,2023-06-02,Delhi,6000,June,0.017408,74666.666667,31.0,1559500
39,1040,Mobile,Electronics,1,22000,2023-06-03,Pune,22000,June,0.079304,11000.000000,22.0,1581500
18,1019,Keyboard,Accessories,1,1500,2023-06-05,Mumbai,1500,June,0.000000,23000.000000,38.5,1583000
29,1030,Laptop,Electronics,2,65000,2023-06-10,Mumbai,130000,June,0.497099,83333.333333,4.0,1745000
12,1013,Smartwatch,Accessories,3,8000,2023-06-10,Chennai,24000,June,0.087041,40666.666667,19.0,1607000
37,1038,Smartwatch,Accessories,1,8000,2023-06-10,Pune,8000,June,0.025145,5833.333333,26.5,1615000
20,1021,Headphones,Accessories,3,2500,2023-06-13,Chennai,7500,June,0.023211,8333.333333,28.5,1752500
17,1018,Tablet,Electronics,2,30000,2023-06-21,Pune,60000,June,0.226306,29833.333333,13.5,1812500
33,1034,Keyboard,Accessories,1,1500,2023-06-24,Chennai,1500,June,0.000000,11833.333333,38.5,1814000
13,1014,Tablet,Electronics,2,30000,2023-06-30,Delhi,60000,June,0.226306,30666.666667,13.5,1874000

### Q29. Export cleaned and enriched dataset to CSV.

In [114]:
# Write your answer here
data.to_csv("sales_data_final.csv", index=False)

### Q30. Write one insight you observed from the analysis (comment cell).

In [116]:
# Write your answer here
# Laptops generate highest revenue despite lower quantity,
# indicating high ticket size products drive revenue more than volume.